name: Test python versions
on:
  push:
    branches:
      - master
      - "*" # matches every branch that doesn't contain a '/'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check directory
        uses: actions/checkout@v2

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          make requirements

      - name: Perfom tests with Tox
        run: tox
