name: Testing in different Python versions with Tox during PR.
on:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
      - name: Check directory
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          make requirements

      - name: Tox
        run: |
          tox -p auto -- -v -k "not ENV"
